### ISSUE TITLE
CanSendOrderConfirmationEmail

### ISSUE THREAD

**Issue by Shoprunners** [Invertus/saferpayofficial#141]
Hi, there is a fatal error:
---
PS: 1.7.7.8
PHP-Version 7.3.33
---

thrown when a payment method was chosen:

it says CanSendOrderConfirmationEmail->verify expects an "Order" object" not an "OrderCore"

file src/Core/Order/Verficiation/CanSendOrderConfirmationEmail

thrown in saferpayofficial.php

 if ($params['template'] === 'order_conf') {
            return $canSendOrderConfirmationEmail->verify($order, (int) $order->current_state);
        }

If I change the class in "CanSendOrderConfirmationEmail" to the expected, it works for me.

**Comment by justelis22** [comment]
Hi there @Shoprunners,

We will check this issue and get back to you as soon as possible.

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there @Shoprunners,

The issue is fixed in the latest [1.2.1 release.](https://github.com/Invertus/saferpayofficial/releases/tag/v1.2.1)

We will be waiting for your feedback!

Best Regards,
Invertus Support team.

**Comment by Djohel** [comment]
Hello,

We're still experiencing the issue. In the saferpayofficial.php file of the Saferpay Official module, specifically in the hookActionEmailSendBefore, before sending the order_conf email, a check is made on order->current_state. However, at this stage, the order status has not yet been updated, resulting in the email not being sent.

On the other hand, the ActionOrderStatusUpdate hook correctly checks using newOrderStatus before proceeding.

We suggest updating the logic in the hookActionEmailSendBefore hook to properly consider the change in order status, similar to the check performed in the ActionOrderStatusUpdate hook Or use actionOrderStatusPostUpdate instead so the order current_state will be changed. 

Suggestions or corrections are welcome.

Best regards

**Comment by justelis22** [comment]
Hi @Djohel,

Thank you for the additional information.

Do you mean you still receive the same error with the 1.2.1 module version? If so, could you attach the steps to recreate the issue and a screenshot of your module configuration?

I have also forwarded it to our development team and as soon as we analyze this comment, I will get back to you with an update.

Best Regards,
Invertus Support team.

**Comment by Shoprunners** [comment]
I can confirm this behaviour. No Mails sent. Mail Alert module is not sending mails to owner as well when saferpay order was created. All other modules and manual orders work

**Comment by justelis22** [comment]
Thanks for the additional information, I will forward this to our developers to analyze further.

Best Regards,
Invertus Support team.

**Comment by didz1809** [comment]
Hello,

Any news on this issue ?

**Comment by justelis22** [comment]
Hi there @didz1809,

During testing this fix, we found a couple of issues, so we are currently in the process of development.

We should release the beta this week.

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there @Shoprunners @Djohel @didz1809, thank you for your patience and understanding.

We have prepared a beta release for version 1.2.2. It is available here - https://github.com/Invertus/saferpayofficial/releases/tag/v1.2.2-beta

All of the issues should be fixed, however, we would appreciate it if you could install the module on your development store to verify this.

The release was tested by our QA department and this is the final version, if we don't receive any negative feedback, we will release the module officially next week.

Best Regards,
Invertus Support team

**Comment by justelis22** [comment]
Closing as the 1.2.2 is officially released now.
